CHANGELOG.MD
lib/ACF/PageGroup.php
lib/ACFController.php
lib/ThemeController.php
models/page.php

Add use overlay setting for pages
TMS-143

TMS-143: Add use overlay setting

---

CHANGELOG.MD
lib/ACF/ArtistGroup.php
lib/ACF/ArtworkGroup.php
lib/ACF/ArtworkLocationGroup.php
lib/Localization.php
lib/PostType/Artist.php
lib/PostType/Artwork.php
lib/Taxonomy/ArtistCategory.php
lib/Taxonomy/ArtworkLocation.php
lib/Taxonomy/ArtworkType.php
lib/ThemeController.php

Artist CPT & Artwork CPT
TMS-133

TMS-133: Artist CPT & Artwork CPT

---

CHANGELOG.MD
assets/styles/main.scss
assets/styles/utils/_rounded-image.scss
assets/styles/utils/index.scss
lib/ACF/AlterCallToActionLayout.php

Alter Call to Action layout
TMS-141

TMS-141: Alter Call to Action layout

---

assets/styles/theme-muumimuseo.scss
lib/PostType/Artist.php
lib/Taxonomy/ArtistCategory.php
lib/TaxonomyController.php
lib/ThemeController.php
models/single-artist.php
partials/shared/additional-info-list.dust
partials/shared/additional-info-row.dust
partials/shared/artwork-list.dust
partials/single-artist.dust

Adds single artist view.
TMS-133

TMS-133: Single Artist

---

CHANGELOG.MD
assets/styles/theme-muumimuseo.scss
lib/ACF/ArtworkGroup.php
lib/ACF/Fields/Settings/ArtworkSettingsTab.php
lib/ACF/SettingsGroup.php
lib/PostType/Artist.php
lib/PostType/Artwork.php
lib/ThemeController.php
lib/ThemeSupports.php
models/archive-artist.php
models/archive-artwork.php
partials/archive-artist.dust
partials/archive-artwork.dust
partials/shared/archive-filters.dust
partials/shared/archive-pagination.dust
partials/shared/archive-view-title.dust

TMS-135: Artwork archive

---

lib/RolesController.php
lib/Taxonomy/ArtistCategory.php
lib/Taxonomy/ArtworkLocation.php
lib/Taxonomy/ArtworkType.php
lib/ThemeController.php

Add caps for Artist and Artwork
TMS-197

TMS-197: Add caps for Artist and Artwork

---

assets/styles/overrides.scss
lang/tms-theme-muumimuseo.pot
lib/ACF/ArtworkGroup.php
lib/Assets.php
lib/Localization.php
lib/PostType/Artist.php
lib/PostType/Artwork.php
models/archive-artwork.php
models/single-artist.php
models/single-artwork.php
partials/shared/additional-info-list.dust
partials/shared/additional-info-row.dust
partials/shared/artwork-gallery.dust
partials/single-artist.dust
partials/single-artwork.dust
style.css

Adds Single Artwork view.
TMS-134

TMS-134: Single Artwork view

---

CHANGELOG.MD
assets/styles/layouts/image-carousel.scss
assets/styles/layouts/index.scss
assets/styles/main.scss
lib/ACF/AlterImageCarousel.php
partials/layouts/layout-image-carousel.dust

Adds Rectangle (default) and Rounded choices to Image Carousel.
TMS-142

TMS-142: Image Carousel Customization

---

CHANGELOG.MD
assets/assets_test.html
assets/styles/_color_overrides.scss
assets/styles/base/_base.scss
assets/styles/main.scss
assets/styles/overrides/_button.scss
assets/styles/overrides/_grid.scss
assets/styles/overrides/_icon-links.scss
assets/styles/overrides/_logo-wall.scss
assets/styles/overrides/_sibling-navigation.scss
assets/styles/overrides/index.scss
assets/styles/settings/_settings.scss
assets/styles/settings/brand/_colors.scss
assets/styles/theme-muumimuseo.scss
lib/ACF/AlterArticlesLayout.php
lib/ACF/AlterCallToActionLayout.php
lib/ACF/AlterImageCarouselLayout.php
lib/ACF/Field/AccentColorField.php
lib/ThemeCustomizationController.php
partials/views/home/home-grid-item.dust

Modified element colors to match design.
TMS-137

TMS-137: Color theme changes

---

CHANGELOG.MD
partials/shared/footer-back-to-top.dust

Fix back-to-top button text wrapping in iOS
TMS-199

TMS-199: Fix back-to-top button text wrapping in iOS

---

CHANGELOG.MD
lib/ACF/ArtistGroup.php
lib/ACF/ArtworkGroup.php
lib/ACF/Fields/Settings/ArtistSettingsTab.php
lib/ACF/Fields/Settings/ArtworkSettingsTab.php
lib/ACF/SettingsGroup.php
models/single-artwork.php
partials/shared/additional-info-list.dust
partials/shared/additional-info-row.dust

TMS-216: Pre fill artist & artwork additional information from settings

---

CHANGELOG.MD
assets/styles/_color_overrides.scss
assets/styles/overrides/_search.scss
assets/styles/overrides/index.scss
lib/ThemeCustomizationController.php

Setup search results colors
TMS-213
TMS-10

TMS-213: Search results

---

CHANGELOG.MD
assets/styles/overrides/_accessible-slick.scss
assets/styles/overrides/_image-gallery.scss
assets/styles/overrides/index.scss

- Override focus styles for Image gallery block and Image carousel layout
TMS-285 (CR: TMS-10)

TMS-285: Override focus styles for Image gallery block and Image carousel layout

---

CHANGELOG.MD
assets/styles/overrides/_link-list.scss
assets/styles/overrides/index.scss

fix/link-list-block: Fix link list block styles

---

CHANGELOG.MD
assets/styles/layouts/_hero.scss
partials/layouts/layout-hero.dust

TMS-303: Adjust hero height

---

CHANGELOG.MD
lib/ACF/ArtistGroup.php
package-lock.json
partials/single-artist.dust

[https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
Changes to single artist's layout. Added field for short description.
Client apparently wanted short description in addition to description field. Therefore, the elements' order on the page had to be changed as well. 
[https://geniemdev.atlassian.net/browse/TMS-357](https://geniemdev.atlassian.net/browse/TMS-357)
Tested visually and by comparing Figma to staging sites
Tested with `composer lint-all `

TMS 357 Taitelija-sivun muutokset

---

CHANGELOG.MD
partials/shared/additional-info-row.dust
partials/single-artist.dust

[https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
Font fix for single artist's page's table element.
The text styles were different than in Figma.
[https://geniemdev.atlassian.net/browse/TMS-358](https://geniemdev.atlassian.net/browse/TMS-358)
Tested visually and by comparing Figma to staging sites
Tested with composer lint-all

TMS 358-2 Taulukossa on liian pieni ja väärä fontti

---

CHANGELOG.MD
partials/views/search/form.dust

TMS-371: Remove search filters

---

CHANGELOG.MD
partials/layouts/layout-hero.dust

TMS-318-1: Avoid heading level increase

---

CHANGELOG.MD
assets/styles/overrides/_subpages.scss
assets/styles/overrides/index.scss
lib/ThemeCustomizationController.php

TMS-373: Fix subpages styles

---

CHANGELOG.MD
assets/styles/theme-muumimuseo.scss

Fix secondary accent color
TMS-372

TMS-372: Fix secondary accent color

---

CHANGELOG.MD
assets/styles/_color_overrides.scss
assets/styles/overrides/_language-nav.scss
assets/styles/overrides/index.scss

TMS-375: Fix language navigation styles

---

CHANGELOG.MD
assets/styles/base/_typography.scss
assets/styles/base/index.scss
assets/styles/overrides/_call-to-action.scss
assets/styles/overrides/_content-columns.scss
assets/styles/overrides/_grid.scss
assets/styles/overrides/_icon-links.scss
assets/styles/overrides/_map.scss
assets/styles/overrides/_notice-banner.scss
assets/styles/overrides/index.scss

TMS-376: Fix layout fonts

---

CHANGELOG.MD
assets/styles/overrides/_pill.scss
partials/views/page-events-calendar/page-events-calendar-item-grid.dust
partials/views/page-events-calendar/page-events-calendar-item-list.dust

TMS-374: Fix event list styles

---

CHANGELOG.MD
assets/styles/layouts/image-carousel.scss

CR: [https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
Styles to fix highlighting in image carousel. Opacity transition replaced with filter transition.
[TMS-361](https://geniemdev.atlassian.net/browse/TMS-361)
Browsestack, latest 2 browsers

TMS-361: Fix image carousel's highlighting

---

CHANGELOG.MD
lib/ACF/AlterGridFields.php

Fixed filter to affect also grid layout in addition to block type grid.
https://geniemdev.atlassian.net/browse/TMS-360
Locally

TMS-360-1115: Fixed filter for grid fields layout changes.

---

CHANGELOG.MD
assets/styles/overrides/_single-artwork.scss
lib/ThemeCustomizationController.php

Quote styles fixed like asked in the sheet: text color and spacing.
[TMS-296](https://geniemdev.atlassian.net/browse/TMS-296)
Browser inspector, visually.

TMS-296: Fix quote styles

---

CHANGELOG.MD
assets/styles/overrides/_header.scss

TMS-302-1: Make the logo bigger

---

CHANGELOG.MD
partials/shared/additional-info-list.dust
partials/shared/additional-info-row.dust

Template conditions that title and text exists for artist's additional info row.  
[https://geniemdev.atlassian.net/browse/TMS-370](https://geniemdev.atlassian.net/browse/TMS-370)
Locally by empty values

TMS-370: Hide Artist's additional info row if title or text empty

---

CHANGELOG.MD
assets/styles/overrides/_language-nav.scss

Fix styles for language dropdown in menu.
[https://geniemdev.atlassian.net/browse/TMS-393](https://geniemdev.atlassian.net/browse/TMS-393)
Locally, stage, browserstack. Mouse and keyboard.

TMS-393: Lang dropdown styles

---

CHANGELOG.MD
assets/styles/overrides/_materials.scss
assets/styles/overrides/index.scss

Overriding materials block styles with CSS in theme
[TMS-389](https://geniemdev.atlassian.net/browse/TMS-389)
Locally, browserstack, android phone.

TMS-389: Override materals block styles set by classes with CSS

---

CHANGELOG.MD
assets/styles/overrides/_forms.scss
assets/styles/overrides/index.scss

TMS-398: Fix form styles

---

CHANGELOG.MD
assets/styles/overrides/_accordion.scss
assets/styles/overrides/index.scss

Fix accordion styles by overriding base theme styles
[TMS-404](https://geniemdev.atlassian.net/browse/TMS-404)
Locally, staging

TMS-404: Fix accordion styles

---

CHANGELOG.MD
assets/styles/_color_overrides.scss
assets/styles/overrides/_header.scss

CR: [https://geniemdev.atlassian.net/browse/TMS-10](https://geniemdev.atlassian.net/browse/TMS-10)
Fix current menu parent underlining in mobile and desktop. Mostly done in base theme.
[TMS-401](https://geniemdev.atlassian.net/browse/TMS-401)
Locally, staging

TMS-401: Fix nav underlining for current menu parent

---

CHANGELOG.MD
assets/styles/overrides/_sibling-navigation.scss

Sibling navigation styles
TMS-403

TMS-403: Sibling navigation styles

---

CHANGELOG.MD
partials/layouts/layout-image-carousel.dust

Image carousel tab index
TMS-414

TMS-414: Image carousel tab index

---

CHANGELOG.MD
partials/views/home/home-grid-item.dust

Fix title link color in post highlights in posts page
[TMS-416](https://geniemdev.atlassian.net/browse/TMS-416)
Locally

TMS-416: Fix title link color in post highlights in posts page

---

CHANGELOG.MD
assets/styles/_color_overrides.scss

Fix active pill hover colors
TMS-477

TMS-477: Fix active pill hover colors

---

CHANGELOG.MD
assets/styles/views/_single.scss
assets/styles/views/index.scss

Improve content link discernibility
TMS-486

TMS-486: Improve content link discernibility

---

CHANGELOG.MD
assets/styles/main.scss
assets/styles/ui-components/_footer.scss
assets/styles/ui-components/index.scss

Fix back to top button hover & focus colors
TMS-487

TMS-487: Fix back to top button hover & focus colors

---

assets/styles/base/_base.scss
assets/styles/layouts/image-carousel.scss
assets/styles/overrides/_articles.scss
assets/styles/overrides/_forms.scss
assets/styles/overrides/_grid.scss
assets/styles/overrides/_image-banner.scss
assets/styles/overrides/_key-figures.scss
assets/styles/overrides/_map.scss
assets/styles/overrides/_notice-banner.scss
assets/styles/overrides/_quote.scss
assets/styles/overrides/_related-posts.scss
assets/styles/overrides/_share-links.scss
assets/styles/overrides/_social-media.scss
assets/styles/overrides/index.scss
assets/styles/views/_single.scss
assets/styles/views/index.scss
lib/ACF/LayoutInfoBadge.php
lib/ThemeCustomizationController.php

TMS-420: General theme fixes

---

CHANGELOG.MD
assets/styles/base/_base.scss

Background eyes visible only with wide screens
TMS-563
Locally

TMS-563: Background eyes visible only with wide screens

---

CHANGELOG.MD
assets/styles/ui-components/_modal.scss

Fix modal button icon fill
TMS-575

TMS-575: Fix modal button icon fill

---

lib/ThemeCustomizationController.php

Fix top level menu trigger
TMS-424

TMS-424: Fix top level menu trigger

---

lib/PostType/Artist.php
lib/PostType/Artwork.php
models/archive-artist.php
models/archive-artwork.php
models/page-artwork.php
models/single-artwork.php

Fix an issue where link to current artist is not present, if the current artwork is the artists' only artwork.
TMS-430

TMS-430: Fix related artwork logic

---

CHANGELOG.MD
partials/single-artist.dust

- [ x ] New feature (non-breaking change which adds functionality)

TMS-300: Swap order of artist short description and additional information.

---

CHANGELOG.MD
models/single-artwork.php

TMS-728: Fix media gallery texts of featured image in artwork.

---

CHANGELOG.MD
models/single-artwork.php
partials/single-artwork.dust

Display image meta in single artwork view
TMS-816

TMS-816: Display image meta in single artwork view

---

CHANGELOG.MD
lib/PostType/Artist.php
lib/PostType/Artwork.php

TMS-813: Translate CPT names

---

CHANGELOG.MD
assets/styles/views/_single.scss
assets/styles/views/index.scss
package-lock.json

TMS-224: Drupal news related styling.

---

CHANGELOG.MD
partials/views/home/home-grid-item.dust
partials/views/home/home-list-item.dust

TMS-880: Display drupal image

---

CHANGELOG.MD
lib/ACF/Fields/Settings/HeaderSettingsMainMenuTab.php
lib/ACF/SettingsGroup.php
lib/ThemeSupports.php
models/archive-artwork.php
models/shared/header.php
partials/shared/header-inner.dust
partials/ui/menu/fly-out-nav.dust
partials/ui/menu/main-menu.dust

TMS-733: Replace core menu by acf repeater

---

CHANGELOG.MD
partials/views/home/home-highlight.dust

CR: https://geniemdev.atlassian.net/browse/PIEN-7610

PIEN-7610: Fix showing images in highlight block

---

CHANGELOG.MD
assets/styles/overrides/_accordion.scss
assets/styles/overrides/_image.scss
assets/styles/overrides/_single-artwork.scss
assets/styles/overrides/_single-post.scss
assets/styles/overrides/index.scss
assets/styles/settings/_settings.scss
partials/layouts/layout-accordion-image.dust
partials/layouts/layout-content-columns.dust
partials/shared/artwork-list.dust
partials/single-artist.dust
partials/single-artwork.dust
partials/single.dust

TMS-818: Fix images

---

CHANGELOG.MD
models/shared/header.php

Task: https://geniemdev.atlassian.net/browse/PIEN-8572
Add missing body-script from setting-fields to use

PIEN-8572: Add missing body-script to use

---

CHANGELOG.MD
partials/shared/header-inner.dust
style.css

Task: https://geniemdev.atlassian.net/browse/TMS-931
Change main navigation container from div to nav-element

TMS-931: Navigation accessibility fix

---

CHANGELOG.MD
partials/layouts/layout-image-carousel.dust
style.css

Task: https://hiondigital.atlassian.net/browse/TMS-936
Image carousel layout accessibility fixes

TMS-936: Image carousel accessibility fixes

---

CHANGELOG.MD
partials/layouts/layout-content-columns.dust

Task: https://hiondigital.atlassian.net/browse/TMS-970
Add image meta to content-columns component

TMS-970: Add image meta to content-columns component

---

CHANGELOG.MD
assets/styles/base/_base.scss
style.css

Task: https://hiondigital.atlassian.net/browse/TMS-997
Change textblock button border-color if no bg-color is selected

TMS-997: Change textblock-layout button style

---

CHANGELOG.MD
partials/shared/header-inner.dust
partials/ui/menu/fly-out-nav.dust
partials/ui/menu/main-menu.dust
style.css

Severa-ID: 2247
Severa-kuvaus: TMS-1015 Saavutettavuuskorjauksia
Task: https://hiondigital.atlassian.net/browse/TMS-1015
Fix missing string in menu-toggle button, fix escaping filters

TMS-1015: Header accessibility fixes

---

CHANGELOG.MD
assets/styles/overrides/_accordion.scss

Severa-kuvaus: TMS-1044 Haitarilohkoon kehitystä
Task: https://hiondigital.atlassian.net/browse/TMS-1044
- Accordion new functionality style overrides

TMS-1044: Accordion style changes

---

CHANGELOG.MD
partials/single.dust

Severa-kuvaus: TMS-1057 Artikkeliin ingressityyli
Task: https://hiondigital.atlassian.net/browse/TMS-1057
Increase articles lead-text font-size

TMS-1057: Increase articles lead-text font-size

---

CHANGELOG.MD
partials/views/page-events-calendar/page-events-calendar-item-grid.dust
partials/views/page-events-calendar/page-events-calendar-item-list.dust

Severa-kuvaus: TMS-1100 Tapahtumaan useampi paikka näkyviin
Task: https://hiondigital.atlassian.net/browse/TMS-1100
- Show multiple locations for events if available
- Add "and other locations" text in event-highlights if multiple locations exist

TMS-1100: Show multiple locations for events if available

---

CHANGELOG.MD
partials/layouts/layout-content-columns.dust
partials/ui/image/image-meta-minimal.dust

Severa-kuvaus: TMS-1114 Kuvaaja-tiedot näkyviin myös Palstat-komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-1114
Change image-meta on content-columns component

TMS-1114: Change image-meta on cta- & content-columns components

---

CHANGELOG.MD
assets/styles/ui-components/_duetdatepicker.scss
assets/styles/views/_event-search.scss

Severa-ID: 2247
Severa-kuvaus: TMS-1131 Tapahtumahaku-sivupohjan hakusana-kentästä puuttuu reunat
Task: https://hiondigital.atlassian.net/browse/TMS-1131
Fix event search form styles, modify duet-datepicker style overrides

TMS-1131: Events search form style changes

---

CHANGELOG.MD
assets/scripts/hero.js
assets/scripts/theme-muumimuseo.js
assets/styles/layouts/_hero.scss
lib/ACF/Layouts/HeroLayout.php
partials/layouts/layout-hero.dust

Severa-kuvaus: TMS-1172 Kehitystä heron videoon, tietyt teemat
Task: https://hiondigital.atlassian.net/browse/TMS-1172
Add video-possibility to hero-layout

TMS-1172: Add video-fields and functionality to hero-component

---

CHANGELOG.MD
assets/styles/base/_base.scss
assets/styles/overrides/_sibling-navigation.scss

Severa-ID: 2247
Severa-kuvaus: TMS-1160 Saavutettavuus: Vapriikin kohdistuksia puuttuu + muutoksia niihin
Task: https://hiondigital.atlassian.net/browse/TMS-1160
Improve focus outlines for elements to improve accessibility

TMS-1160: Fix elements focus outline thickness
